version: "3.9"
   
services:
  app:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
 
  db:
    image: postgres:14-alpine
    restart: always
    container_name: postgres_container3
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env.dev

  redis:
    image: redis:alpine
  celery:
    build:
      context: .
    restart: always
    volumes:
      - .:/app
    command: celery -A core worker -l INFO
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - app
volumes:
  pgdata: