# Generated by Django 4.0.4 on 2022-04-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, verbose_name='Url')),
                ('short_url', models.URLField(max_length=255, verbose_name='Url-short')),
            ],
        ),
    ]
